"""Core state definition for the multi-agent system."""

from typing import Any, Dict, List, Literal, TypedDict, Annotated
from operator import add


class AgentState(TypedDict):
    """State that flows through the LangGraph workflow.

    This state is managed by LangGraph and passed between agents.
    It follows the "file system as memory" pattern - artifacts are stored
    in the workspace directory, and only file paths are kept in state.
    """

    # Input
    requirement: str
    """Original user requirement/input."""

    # PRD Phase
    prd_content: str
    """Generated PRD content."""
    prd_file_path: str
    """Path to PRD.md file in workspace."""
    prd_feedback: str
    """Human feedback on PRD (empty if no feedback)."""
    prd_iteration: int
    """Number of PRD iteration cycles."""

    # Design Phase
    design_content: str
    """Generated technical design content."""
    design_file_path: str
    """Path to Design.md file in workspace."""
    design_feedback: str
    """Human feedback on design (empty if no feedback)."""
    design_iteration: int
    """Number of design iteration cycles."""

    # Task Breakdown
    task_list: List[Dict[str, Any]]
    """List of atomic tasks generated by architect.

    Each task should have:
    - id: str - Unique task identifier
    - title: str - Task title
    - description: str - Detailed description
    - dependencies: List[str] - IDs of tasks this depends on
    - status: str - One of: pending, in_progress, completed, blocked
    - priority: int - Higher number = higher priority
    """
    current_task_index: int
    """Index of currently executing task in task_list."""
    completed_tasks: List[str]
    """List of completed task IDs."""

    # Code Generation Phase
    code_directory: str
    """Directory where generated code is stored."""
    coding_iterations: int
    """Number of coding iterations completed."""
    coding_output: str
    """Output from Claude Code CLI."""

    # Testing Phase (for future QA agent)
    test_cases: str
    """Generated test cases."""
    test_results: str
    """Test execution results."""

    # Bug Fix Phase (for future bug fix agent)
    bugs: List[Dict[str, Any]]
    """List of discovered bugs.

    Each bug should have:
    - id: str - Unique bug identifier
    - description: str - Bug description
    - severity: str - One of: critical, high, medium, low
    - status: str - One of: open, in_progress, fixed, verified
    - location: str - File/function where bug occurs
    """
    bug_fix_output: str
    """Output from bug fixing attempts."""

    # Workflow Control
    stage: Literal["prd", "design", "dev", "test", "bug_fix", "done"]
    """Current workflow stage."""
    session_id: str
    """Unique session identifier for this workflow run."""

    # Message History (for LangGraph checkpointing)
    messages: Annotated[List[str], add]
    """Accumulated messages for debugging/audit trail."""

    # Error Handling
    error: str
    """Error message if something went wrong."""
    retry_count: int
    """Number of retries attempted for current operation."""

    # Human Interaction
    waiting_for_human: bool
    """Whether the system is waiting for human input."""
    human_feedback: str
    """Feedback provided by human."""


def create_initial_state(requirement: str, session_id: str) -> AgentState:
    """Create an initial state for a new workflow.

    Args:
        requirement: The user's requirement/description
        session_id: Unique session identifier

    Returns:
        Initial AgentState with all fields set to defaults
    """
    return {
        # Input
        "requirement": requirement,

        # PRD Phase
        "prd_content": "",
        "prd_file_path": "",
        "prd_feedback": "",
        "prd_iteration": 0,

        # Design Phase
        "design_content": "",
        "design_file_path": "",
        "design_feedback": "",
        "design_iteration": 0,

        # Task Breakdown
        "task_list": [],
        "current_task_index": 0,
        "completed_tasks": [],

        # Code Generation Phase
        "code_directory": "",
        "coding_iterations": 0,
        "coding_output": "",

        # Testing Phase
        "test_cases": "",
        "test_results": "",

        # Bug Fix Phase
        "bugs": [],
        "bug_fix_output": "",

        # Workflow Control
        "stage": "prd",
        "session_id": session_id,
        "messages": [],

        # Error Handling
        "error": "",
        "retry_count": 0,

        # Human Interaction
        "waiting_for_human": False,
        "human_feedback": "",
    }
